---
- name: Pull btre_project from github
  git:
    repo: https://github.com/Mossie93/btre_architecture.git
    dest: /home/app/btre_project
- name: Ensure btre_project belongs to app user
  file:
    name: /home/app/btre_project
    owner: app
    state: directory  
- name: Install gunicorn
  pip:
    chdir: /home/app/btre_project
    name: gunicorn
- name: Install requirements
  pip:
    chdir: /home/app
    virtualenv: /home/app/venv
    requirements: btre_project/requirements.txt
- name: Upload settings file
  template:
    src: local_settings.py.j2
    dest: /home/app/btre_project/btre/local_settings.py
- name: Create migrations
  command: python manage.py makemigrations
  args:
    chdir: /home/app/btre_project
- name: Run migrations
  command: python manage.py migrate
  args:
    chdir: /home/app/btre_project
- name: Create static files
  command: python manage.py collectstatic
  args:
    chdir: /home/app/btre_project
- name: Start gunicorn
  command: systemctl start gunicorn.socket
  become: yes
- name: Enable gunicorn
  command: systemctl enable gunicorn.socket
  become: yes

