---
- name: Pull btre_project from github
  git:
    repo: https://github.com/Mossie93/btre_project.git
    dest: /home/app/btre_project  
- name: Install virtualenv
  pip:
    chdir: /home/app/btre_project
    name: virtualenv
    executable: pip3
- name: Install gunicorn
  pip:
    chdir: /home/app/btre_project
    name: gunicorn
    virtualenv: /home/app/venv
    virtualenv_python: python3
- name: Install requirements
  pip:
    chdir: /home/app
    virtualenv: /home/app/venv
    virtualenv_python: python3
    requirements: btre_project/requirements.txt
- name: Upload settings file
  template:
    src: local_settings.py.j2
    dest: /home/app/btre_project/btre/local_settings.py
- name: Ensure /home/app belongs to app user
  file:
    name: /home/app/
    owner: app
    group: app
    recurse: yes
    state: directory
- name: Run migrations
  become: yes
  become_user: app
  django_manage:
    app_path: /home/app/btre_project
    command: migrate
    virtualenv: /home/app/venv
- name: Create static files
  become: yes
  become_user: app
  django_manage:
    app_path: /home/app/btre_project
    command: collectstatic
    virtualenv: /home/app/venv
- name: Upload gunicorn socket config file
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket
- name: Upload gunicorn service config file
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
- name: Start gunicorn
  command: systemctl start gunicorn.socket
  become: yes
- name: Enable gunicorn
  command: systemctl enable gunicorn.socket
  become: yes

