---
- hosts: webservers
  remote_user: root
  vars:
    ansible_ssh_private_key_file: "{{ root_user_private_key_path }}"
  roles:
    - common
- hosts: webservers
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ admin_user_private_key_path }}"
  roles:
    - postgres
    - gunicorn
    - nginx


